service: everydayparks


provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 120
  environment:
    GOOGLE_API: ${env:GOOGLE_API}
    BEARER_TOKEN: ${env:BEARER_TOKEN}
    CONSUMER_KEY: ${env:CONSUMER_KEY}
    CONSUMER_SECRET: ${env:CONSUMER_SECRET}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    ACCESS_SECRET: ${env:ACCESS_SECRET}
    OAUTH_CLIENT_ID: ${env:OAUTH_CLIENT_ID}
    OAUTH_SECRET: ${env:OAUTH_SECRET}
    TWITTER_USER_ID: ${env:TWITTER_USER_ID}
  iam:
    role:
      name: everydayparks-dev-${self:provider.region}-lambdaRole
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParametersByPath"
            - "ssm:PutParameter"
          Resource:
            - "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/everydayparks/rateLimitReset"

functions:
  sendRandomPark:
    handler: handler.sendRandomPark
    events:
      - schedule: cron(30 * * * ? *)
    maximumRetryAttempts: 1
  sendRandomNationalPark:
    handler: handler.sendRandomNationalPark
    events:
      - schedule: cron(0 17 ? * SUN *)
    maximumRetryAttempts: 1
  sendRandomNationalForest:
    handler: handler.sendRandomNationalForest
    events:
      - schedule: cron(0 17 ? * MON *)
    maximumRetryAttempts: 1
  sendRandomNationalMonument:
    handler: handler.sendRandomNationalMonument
    events:
      - schedule: cron(0 17 ? * TUE *)
    maximumRetryAttempts: 1
  sendRandomProtectedArea:
    handler: handler.sendRandomProtectedArea
    events:
      - schedule: cron(0 17 ? * THU *)
    maximumRetryAttempts: 1
  sendRandomStatePark:
    handler: handler.sendRandomStatePark
    events:
      - schedule: cron(0 16 * * ? *)
    maximumRetryAttempts: 1
  sendRandomHistoricLandmark:
    handler: handler.sendRandomHistoricLandmark
    events:
      - schedule: cron(0 18 * * ? *)
    maximumRetryAttempts: 1
